site_name: DecAPI Documentation
site_author: Decicus
site_description: Documentation for DecAPI.
site_url: https://documentation.decapi.dev
theme:
  name: material
  custom_dir: custom
  features:
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Blog:
    - 'blog/index.md'
  - Contact: 'contact.md'
  - Documentation:
    - 'BetterTTV':
      - 'List channel emotes': 'bttv/channel-emotes.md'
    - 'DayZ':
      - 'Get latest blog post': 'dayz/news.md'
      - 'Map search via iZurvive': 'dayz/izurvive.md'
      - "Query a PC server's current player count": 'dayz/players.md'
    - 'FrankerFaceZ':
      - 'List channel emotes': 'ffz/channel-emotes.md'
    - 'Math':
      - 'Evaluate math expression': 'math/index.md'
    - 'Miscellaneous':
      - 'Convert currency': 'misc/currency.md'
      - 'Current time in timezone': 'misc/time.md'
      - 'Time difference between two timestamps': 'misc/time-difference.md'
    - 'Random':
      - 'Generate random number': 'random/number.md'
    - 'Steam':
      - 'Global player count for a game': 'steam/global-players.md'
      - 'Your total playtime in a specified game': 'steam/hours.md'
    - 'Twitch':
      - 'Account age': 'twitch/accountage.md'
      - 'Avatar URL': 'twitch/avatar.md'
      - 'Account creation date and time': 'twitch/creation.md'
      - 'Follow age / follow length': 'twitch/followage.md'
      - 'Follow count': 'twitch/followcount.md'
      - 'Followed date and time': 'twitch/followed.md'
      - 'Game': 'twitch/game.md'
      - 'Latest video highlight': 'twitch/highlight.md'
      - 'User ID': 'twitch/id.md'
  - 'Cached Endpoints': 'cached-endpoints.md'
  - 'Rate limits': 'rate-limits.md'
  - 'Server Setup & Costs': 'server-setup.md'
plugins:
  - macros:
  - blog:
      archive: false
extra:
  # Macros
  base_url: "https://decapi.me"

  # Configurations
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Decicus/DecAPI-Docs
      name: DecAPI documentation's GitHub repository
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/decapi.me
      name: DecAPI's Bluesky profile
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/Decicus
      name: Decicus' Patreon page for supporting development
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/decic.us
      name: Decicus' personal Bluesky profile
    - icon: fontawesome/brands/discord
      link: https://decapi.link/discord
      name: DecAPI's Discord server
    - icon: fontawesome/brands/github
      link: https://github.com/Decicus/DecAPI
      name: DecAPI's GitHub repository
extra_css:
  - stylesheets/custom.css
extra_javascript:
  - js/matomo.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
