site_name: DecAPI Docs
site_author: Decicus
site_description: Documentation for DecAPI.
site_url: https://documentation.decapi.me
theme:
  name: material
  custom_dir: custom
  features:
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - 'Blog / Updates': 'blog/index.md'
  - Documentation:
    - 'BetterTTV':
      - 'List channel emotes': 'bttv/channel-emotes.md'
    - 'DayZ':
      - 'Get latest blog post': 'dayz/news.md'
      - 'Map search via iZurvive': 'dayz/izurvive.md'
      - "Query a PC server's current player count": 'dayz/players.md'
plugins:
  - macros:
  - blog:
      archive: false
extra:
  # Macros
  base_url: "https://decapi.me"

  # Configurations
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Decicus/DecAPI-Docs
      name: DecAPI documentation's GitHub repository
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Decicus
      name: Decicus' personal Twitter account
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/Decicus
      name: Decicus' Patreon page for supporting development
    - icon: fontawesome/brands/discord
      link: https://decapi.link/discord
      name: DecAPI's Discord server
    - icon: fontawesome/brands/github
      link: https://github.com/Decicus/DecAPI
      name: DecAPI's GitHub repository
extra_css:
  - stylesheets/custom.css
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
