site_name: DecAPI Docs
theme:
  name: material
  features:
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - 'Blog': blog
  - Documentation:
    - 'BetterTTV': 'bttv/emotes'
plugins:
  - blog:
      archive: false
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Decicus/DecAPI-Docs
      name: DecAPI documentation's GitHub repository
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Decicus
      name: Decicus' personal Twitter account
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/Decicus
      name: Decicus' Patreon page for supporting development
    - icon: fontawesome/brands/discord
      link: https://decapi.link/discord
      name: DecAPI's Discord server
    - icon: fontawesome/brands/github
      link: https://github.com/Decicus/DecAPI
      name: DecAPI's GitHub repository
extra_css:
  - stylesheets/custom.css